version: "3.8"
services:
  app:
    image: usanzadunje/ionic-prod
    container_name: frontend-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - app-data:/etc/nginx
    ports:
      - 80:80
#      - 443:443

volumes:
  app-data: