version: "3.8"
services:
  app:
    image: usanzadunje/ionic-dev
    container_name: frontend-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8100:8100
    command: npm run ionic-serve